################################################################################
# Automatically-generated file. Do not edit!
################################################################################

S79_SRCS := 
ASM_SRCS := 
CPP_SRCS := 
S79_UPPER_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
OBJS := 
C_UPPER_DEPS := 
CXX_DEPS := 
C_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
. \
autogen \
gecko_sdk_4.4.3/hardware/board/src \
gecko_sdk_4.4.3/hardware/driver/configuration_over_swo/src \
gecko_sdk_4.4.3/hardware/driver/mx25_flash_shutdown/src/sl_mx25_flash_shutdown_usart \
gecko_sdk_4.4.3/platform/CMSIS/RTOS2/Source \
gecko_sdk_4.4.3/platform/Device/SiliconLabs/EFR32MG24/Source \
gecko_sdk_4.4.3/platform/bootloader/api \
gecko_sdk_4.4.3/platform/bootloader/app_properties \
gecko_sdk_4.4.3/platform/common/src \
gecko_sdk_4.4.3/platform/common/toolchain/src \
gecko_sdk_4.4.3/platform/driver/debug/src \
gecko_sdk_4.4.3/platform/emdrv/dmadrv/src \
gecko_sdk_4.4.3/platform/emdrv/gpiointerrupt/src \
gecko_sdk_4.4.3/platform/emdrv/nvm3/src \
gecko_sdk_4.4.3/platform/emdrv/ustimer/src \
gecko_sdk_4.4.3/platform/emlib/src \
gecko_sdk_4.4.3/platform/micrium_os/common/source/collections \
gecko_sdk_4.4.3/platform/micrium_os/common/source/common \
gecko_sdk_4.4.3/platform/micrium_os/common/source/kal \
gecko_sdk_4.4.3/platform/micrium_os/common/source/lib \
gecko_sdk_4.4.3/platform/micrium_os/common/source/logging \
gecko_sdk_4.4.3/platform/micrium_os/common/source/platform_mgr \
gecko_sdk_4.4.3/platform/micrium_os/common/source/ring_buf \
gecko_sdk_4.4.3/platform/micrium_os/common/source/rtos \
gecko_sdk_4.4.3/platform/micrium_os/cpu/source \
gecko_sdk_4.4.3/platform/micrium_os/kernel/source \
gecko_sdk_4.4.3/platform/micrium_os/ports/source/generic \
gecko_sdk_4.4.3/platform/micrium_os/ports/source/gnu \
gecko_sdk_4.4.3/platform/peripheral/src \
gecko_sdk_4.4.3/platform/radio/mac/rail_mux \
gecko_sdk_4.4.3/platform/radio/rail_lib/plugin/coexistence/common \
gecko_sdk_4.4.3/platform/radio/rail_lib/plugin/coexistence/hal/efr32 \
gecko_sdk_4.4.3/platform/radio/rail_lib/plugin/coexistence/protocol/ieee802154_uc \
gecko_sdk_4.4.3/platform/radio/rail_lib/plugin/pa-conversions \
gecko_sdk_4.4.3/platform/radio/rail_lib/plugin/rail_util_ant_div \
gecko_sdk_4.4.3/platform/radio/rail_lib/plugin/rail_util_built_in_phys/efr32xg24 \
gecko_sdk_4.4.3/platform/radio/rail_lib/plugin/rail_util_built_in_phys \
gecko_sdk_4.4.3/platform/radio/rail_lib/plugin/rail_util_dma \
gecko_sdk_4.4.3/platform/radio/rail_lib/plugin/rail_util_power_manager_init \
gecko_sdk_4.4.3/platform/radio/rail_lib/plugin/rail_util_pti \
gecko_sdk_4.4.3/platform/radio/rail_lib/plugin/rail_util_rssi \
gecko_sdk_4.4.3/platform/radio/rail_lib/plugin/rail_util_sequencer \
gecko_sdk_4.4.3/platform/security/sl_component/se_manager/src \
gecko_sdk_4.4.3/platform/security/sl_component/sl_mbedtls_support/src \
gecko_sdk_4.4.3/platform/security/sl_component/sl_protocol_crypto/src \
gecko_sdk_4.4.3/platform/security/sl_component/sl_psa_driver/src \
gecko_sdk_4.4.3/platform/service/cpc/src \
gecko_sdk_4.4.3/platform/service/device_init/src \
gecko_sdk_4.4.3/platform/service/hfxo_manager/src \
gecko_sdk_4.4.3/platform/service/iostream/src \
gecko_sdk_4.4.3/platform/service/legacy_hal/src \
gecko_sdk_4.4.3/platform/service/legacy_hal_wdog/src \
gecko_sdk_4.4.3/platform/service/mem_pool/src \
gecko_sdk_4.4.3/platform/service/mpu/src \
gecko_sdk_4.4.3/platform/service/power_manager/src \
gecko_sdk_4.4.3/platform/service/sleeptimer/src \
gecko_sdk_4.4.3/platform/service/system/src \
gecko_sdk_4.4.3/platform/service/token_manager/src \
gecko_sdk_4.4.3/platform/service/udelay/src \
gecko_sdk_4.4.3/protocol/openthread/platform-abstraction/efr32 \
gecko_sdk_4.4.3/protocol/openthread/platform-abstraction/ncp \
gecko_sdk_4.4.3/protocol/openthread/platform-abstraction/rtos \
gecko_sdk_4.4.3/protocol/zigbee/app/em260 \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/common \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/plugin/af-support \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/plugin/debug-print \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/plugin/green-power-adapter \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/plugin/green-power-client \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/plugin/green-power-common \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/plugin/green-power-server \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/plugin/groups-server \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/plugin/multirail-demo \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/security \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/service-function \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/signature-decode \
gecko_sdk_4.4.3/protocol/zigbee/app/framework/util \
gecko_sdk_4.4.3/protocol/zigbee/app/util/security \
gecko_sdk_4.4.3/protocol/zigbee/app/xncp \
gecko_sdk_4.4.3/protocol/zigbee/stack/config \
gecko_sdk_4.4.3/protocol/zigbee/stack/core \
gecko_sdk_4.4.3/protocol/zigbee/stack/framework \
gecko_sdk_4.4.3/protocol/zigbee/stack/security \
gecko_sdk_4.4.3/protocol/zigbee/stack/stubs \
gecko_sdk_4.4.3/protocol/zigbee/stack/zigbee \
gecko_sdk_4.4.3/util/plugin/security_manager \
gecko_sdk_4.4.3/util/silicon_labs/silabs_core/memory_manager \
gecko_sdk_4.4.3/util/third_party/mbedtls/library \
gecko_sdk_4.4.3/util/third_party/openthread/examples/platforms/utils \
gecko_sdk_4.4.3/util/third_party/openthread/src/core/api \
gecko_sdk_4.4.3/util/third_party/openthread/src/core/common \
gecko_sdk_4.4.3/util/third_party/openthread/src/core/crypto \
gecko_sdk_4.4.3/util/third_party/openthread/src/core/diags \
gecko_sdk_4.4.3/util/third_party/openthread/src/core/instance \
gecko_sdk_4.4.3/util/third_party/openthread/src/core/mac \
gecko_sdk_4.4.3/util/third_party/openthread/src/core/radio \
gecko_sdk_4.4.3/util/third_party/openthread/src/core/thread \
gecko_sdk_4.4.3/util/third_party/openthread/src/core/utils \
gecko_sdk_4.4.3/util/third_party/openthread/src/lib/hdlc \
gecko_sdk_4.4.3/util/third_party/openthread/src/lib/spinel \
gecko_sdk_4.4.3/util/third_party/openthread/src/ncp \
gecko_sdk_4.4.3/util/third_party/printf \
gecko_sdk_4.4.3/util/third_party/printf/src \
gecko_sdk_4.4.3/util/third_party/segger/systemview/SEGGER \

